import { createOpenIdConfiguration } from "@/src/lib/oidc-metadata";
import { getBaseUrl } from "@/src/lib/seo-utils";

export function createAuthMarkdown(issuer = getBaseUrl()): string {
  const configuration = createOpenIdConfiguration(issuer);

  return [
    "# Turkish Dictionary auth.md",
    "",
    "## Audience",
    "",
    "This service supports OAuth 2.0 and OpenID Connect for AI agents acting on behalf of a signed-in Turkish Dictionary user.",
    "",
    "## Discover",
    "",
    `- OpenID Connect metadata: ${issuer}/.well-known/openid-configuration`,
    `- OAuth authorization server metadata: ${issuer}/.well-known/oauth-authorization-server`,
    `- Protected tRPC API metadata: ${issuer}/.well-known/oauth-protected-resource`,
    "",
    "## Register",
    "",
    `Register an OAuth client with ${configuration.registration_endpoint}. Dynamic client registration is enabled.`,
    "",
    "The authorization-server metadata advertises this as the `anonymous` agent-auth method: the agent registers a client without presenting an upstream identity assertion.",
    "",
    "- Public agents use `token_endpoint_auth_method=none` and PKCE.",
    "- Confidential clients receive a `client_id` and `client_secret`; keep the secret private.",
    "- Register every exact HTTPS redirect URI before beginning authorization.",
    "",
    "## Authorize",
    "",
    `Use the claim URI, ${configuration.authorization_endpoint}, to start the authorization code flow. Request the \`openid api\` scopes and use an S256 PKCE code challenge.`,
    "",
    "The claim URI is the standard OAuth user sign-in and consent step, not an OTP claim ceremony. Exchange the returned code at the token endpoint using the registered redirect URI and PKCE verifier.",
    "",
    "## Call the API",
    "",
    `Present the resulting access token to ${issuer}/api/trpc:`,
    "",
    "```http",
    "Authorization: Bearer ACCESS_TOKEN",
    "```",
    "",
    "The `api` scope is required for protected tRPC procedures. Tokens without that scope are not accepted for protected operations. The issued credential is an OAuth `access_token`.",
    "",
    "## Lifecycle",
    "",
    "This service does not expose ID-JAG, verified-email, OTP claim, or credential-revocation endpoints. Re-register a client when its redirect URIs or credentials need to change.",
    "",
  ].join("\n");
}
