services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy-1
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

  app:
    image: ${APP_IMAGE:-furki4/turkish-dictionary-app:latest}
    container_name: app-1
    restart: unless-stopped
    env_file:
      - .env.pi
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=pgbouncer
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=${POSTGRES_USER:-postgres}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_DATABASE=${POSTGRES_DB:-turkish_dictionary}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@pgbouncer:5432/${POSTGRES_DB:-turkish_dictionary}?sslmode=disable
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - pgbouncer

  pgbouncer:
    image: edoburu/pgbouncer:latest
    container_name: pgbouncer-1
    restart: unless-stopped
    environment:
      - DB_USER=${POSTGRES_USER:-postgres}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=db
      - DB_NAME=${POSTGRES_DB:-turkish_dictionary}
      - POOL_MODE=transaction
      - MAX_CLIENT_CONN=100
      - DEFAULT_POOL_SIZE=20
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    container_name: db-1
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB:-turkish_dictionary}
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_INITDB_ARGS=--auth=md5
    volumes:
      - pgdata:/var/lib/postgresql/data
    

volumes:
  pgdata:
  caddy_data:
  caddy_config:
