services:
  netdata:
    image: netdata/netdata:stable
    container_name: netdata
    hostname: furkipie
    restart: unless-stopped
    pid: host
    security_opt:
      - apparmor:unconfined
      - no-new-privileges:true
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "127.0.0.1:19999:19999"
    volumes:
      - netdata-config:/etc/netdata
      - netdata-lib:/var/lib/netdata
      - netdata-cache:/var/cache/netdata
      - /:/host/root:ro,rslave
      - /etc/os-release:/host/etc/os-release:ro
      - /proc:/host/proc:ro
      - /run/dbus:/run/dbus:ro
      - /run/user:/run/user:ro
      - /sys:/host/sys:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - com.centurylinklabs.watchtower.enable=false

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "127.0.0.1:9999:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - com.centurylinklabs.watchtower.enable=false

volumes:
  netdata-config:
  netdata-lib:
  netdata-cache:
