import { type AnalyticConstructionDefinition } from "./types";

export const ANALYTIC_CONSTRUCTION_CATALOG: AnalyticConstructionDefinition[] = [
  {
    id: "verb.analytic.ability.ebil",
    kind: "analytic",
    slot: "analytic",
    sourcePos: "Verb",
    targetPos: "Verb",
    sourceCategories: ["Verb"],
    targetCategory: "Verb",
    group: "AnalyticAbility",
    constructionType: "ability",
    labelKey: "actions.analytic.ability.ebil",
    preview: "-(y)Abil",
    linkerPattern: "/A/",
    linkerPhonologyTriggers: ["buffer_y", "consonant_mutation_trigger"],
    auxiliaryLemma: "bil",
    auxiliarySurface: "bil",
  },
  {
    id: "verb.analytic.celerity.iver",
    kind: "analytic",
    slot: "analytic",
    sourcePos: "Verb",
    targetPos: "Verb",
    sourceCategories: ["Verb"],
    targetCategory: "Verb",
    group: "AnalyticCelerity",
    constructionType: "celerity",
    labelKey: "actions.analytic.celerity.iver",
    preview: "-(y)Iver",
    linkerPattern: "/I/",
    linkerPhonologyTriggers: ["buffer_y", "consonant_mutation_trigger"],
    auxiliaryLemma: "ver",
    auxiliarySurface: "ver",
  },
  {
    id: "verb.analytic.continuative.adur",
    kind: "analytic",
    slot: "analytic",
    sourcePos: "Verb",
    targetPos: "Verb",
    sourceCategories: ["Verb"],
    targetCategory: "Verb",
    group: "AnalyticContinuative",
    constructionType: "continuative",
    labelKey: "actions.analytic.continuative.adur",
    preview: "-(y)Adur",
    linkerPattern: "/A/",
    linkerPhonologyTriggers: ["buffer_y", "consonant_mutation_trigger"],
    auxiliaryLemma: "dur",
    auxiliarySurface: "dur",
  },
  {
    id: "verb.analytic.persistence.akal",
    kind: "analytic",
    slot: "analytic",
    sourcePos: "Verb",
    targetPos: "Verb",
    sourceCategories: ["Verb"],
    targetCategory: "Verb",
    group: "AnalyticPersistence",
    constructionType: "persistence",
    labelKey: "actions.analytic.persistence.akal",
    preview: "-(y)Akal",
    linkerPattern: "/A/",
    linkerPhonologyTriggers: ["buffer_y", "consonant_mutation_trigger"],
    auxiliaryLemma: "kal",
    auxiliarySurface: "kal",
  },
  {
    id: "verb.analytic.progression.agel",
    kind: "analytic",
    slot: "analytic",
    sourcePos: "Verb",
    targetPos: "Verb",
    sourceCategories: ["Verb"],
    targetCategory: "Verb",
    group: "AnalyticProgression",
    constructionType: "progression",
    labelKey: "actions.analytic.progression.agel",
    preview: "-(y)Agel",
    linkerPattern: "/A/",
    linkerPhonologyTriggers: ["buffer_y", "consonant_mutation_trigger"],
    auxiliaryLemma: "gel",
    auxiliarySurface: "gel",
  },
  {
    id: "verb.analytic.approximative.ayaz",
    kind: "analytic",
    slot: "analytic",
    sourcePos: "Verb",
    targetPos: "Verb",
    sourceCategories: ["Verb"],
    targetCategory: "Verb",
    group: "AnalyticApproximative",
    constructionType: "approximative",
    labelKey: "actions.analytic.approximative.ayaz",
    preview: "-(y)Ayaz",
    linkerPattern: "/A/",
    linkerPhonologyTriggers: ["buffer_y", "consonant_mutation_trigger"],
    auxiliaryLemma: "yaz",
    auxiliarySurface: "yaz",
  },
  {
    id: "verb.analytic.serial.ipDur",
    kind: "analytic",
    slot: "analytic",
    sourcePos: "Verb",
    targetPos: "Verb",
    sourceCategories: ["Verb"],
    targetCategory: "Verb",
    group: "AnalyticSerialContinuative",
    constructionType: "serial_continuative",
    labelKey: "actions.analytic.serial.ipDur",
    preview: "-(y)Ip dur",
    linkerPattern: "/Ip/",
    linkerPhonologyTriggers: ["buffer_y", "consonant_mutation_trigger"],
    separator: " ",
    auxiliaryLemma: "dur",
    auxiliarySurface: "dur",
  },
  {
    id: "verb.analytic.serial.ipGit",
    kind: "analytic",
    slot: "analytic",
    sourcePos: "Verb",
    targetPos: "Verb",
    sourceCategories: ["Verb"],
    targetCategory: "Verb",
    group: "AnalyticSerialProgressive",
    constructionType: "serial_progressive",
    labelKey: "actions.analytic.serial.ipGit",
    preview: "-(y)Ip git",
    linkerPattern: "/Ip/",
    linkerPhonologyTriggers: ["buffer_y", "consonant_mutation_trigger"],
    separator: " ",
    auxiliaryLemma: "git",
    auxiliarySurface: "git",
  },
  {
    id: "verb.analytic.serial.ipKal",
    kind: "analytic",
    slot: "analytic",
    sourcePos: "Verb",
    targetPos: "Verb",
    sourceCategories: ["Verb"],
    targetCategory: "Verb",
    group: "AnalyticSerialResultative",
    constructionType: "serial_resultative",
    labelKey: "actions.analytic.serial.ipKal",
    preview: "-(y)Ip kal",
    linkerPattern: "/Ip/",
    linkerPhonologyTriggers: ["buffer_y", "consonant_mutation_trigger"],
    separator: " ",
    auxiliaryLemma: "kal",
    auxiliarySurface: "kal",
  },
];
