import {
  type MorphemeDefinition,
  type MorphemeSlot,
  type PartOfSpeech,
  type RuleId,
  type SuffixKind,
} from "./types";

type MorphemeSeed = {
  id: string;
  labelKey: string;
  preview: string;
  legacySuffixId?: string;
  realizationPattern: string;
  phonologyTriggers?: RuleId[];
  requires?: MorphemeDefinition["requires"];
  blocks?: MorphemeDefinition["blocks"];
  setsFeatures?: MorphemeDefinition["setsFeatures"];
};

function createInflectionMorpheme(
  base: MorphemeSeed & {
    category: MorphemeDefinition["category"];
    slot: MorphemeSlot;
    pos: PartOfSpeech;
    group: string;
  },
): MorphemeDefinition {
  return {
    id: base.id,
    kind: "inflectional",
    category: base.category,
    slot: base.slot,
    sourcePos: base.pos,
    targetPos: base.pos,
    group: base.group,
    labelKey: base.labelKey,
    preview: base.preview,
    legacySuffixId: base.legacySuffixId,
    requires: base.requires,
    blocks: base.blocks,
    realizationPattern: base.realizationPattern,
    phonologyTriggers: base.phonologyTriggers ?? [],
    setsFeatures: base.setsFeatures ?? {},
  };
}

function createDerivationalMorpheme(
  base: MorphemeSeed & {
    sourcePos: PartOfSpeech;
    targetPos: PartOfSpeech;
    group: string;
  },
): MorphemeDefinition {
  return {
    id: base.id,
    kind: "derivational",
    category: "derivation",
    slot: "derivation",
    sourcePos: base.sourcePos,
    targetPos: base.targetPos,
    group: base.group,
    labelKey: base.labelKey,
    preview: base.preview,
    legacySuffixId: base.legacySuffixId,
    requires: base.requires,
    blocks: base.blocks,
    realizationPattern: base.realizationPattern,
    phonologyTriggers: base.phonologyTriggers ?? [],
    setsFeatures: {},
  };
}

export const MORPHEME_CATALOG: MorphemeDefinition[] = [
  createDerivationalMorpheme({
    id: "noun.deriv.lIk",
    sourcePos: "Noun",
    targetPos: "Noun",
    group: "NounToNoun",
    labelKey: "actions.derivation.noun.lIk",
    preview: "-lIk",
    legacySuffixId: "noun.deriv.lIk",
    realizationPattern: "/lIk/",
  }),
  createDerivationalMorpheme({
    id: "noun.deriv.lI",
    sourcePos: "Noun",
    targetPos: "Noun",
    group: "NounToNoun",
    labelKey: "actions.derivation.noun.lI",
    preview: "-lI",
    legacySuffixId: "noun.deriv.lI",
    realizationPattern: "/lI/",
  }),
  createDerivationalMorpheme({
    id: "noun.deriv.sIz",
    sourcePos: "Noun",
    targetPos: "Noun",
    group: "NounToNoun",
    labelKey: "actions.derivation.noun.sIz",
    preview: "-sIz",
    legacySuffixId: "noun.deriv.sIz",
    realizationPattern: "/sIz/",
  }),
  createDerivationalMorpheme({
    id: "noun.deriv.CI",
    sourcePos: "Noun",
    targetPos: "Noun",
    group: "NounToNoun",
    labelKey: "actions.derivation.noun.CI",
    preview: "-CI",
    legacySuffixId: "noun.deriv.CI",
    realizationPattern: "/CI/",
    phonologyTriggers: ["consonant_assimilation"],
  }),
  createDerivationalMorpheme({
    id: "noun.deriv.DAş",
    sourcePos: "Noun",
    targetPos: "Noun",
    group: "NounToNoun",
    labelKey: "actions.derivation.noun.DAş",
    preview: "-DAş",
    legacySuffixId: "noun.deriv.DAş",
    realizationPattern: "/DAş/",
    phonologyTriggers: ["consonant_assimilation"],
  }),
  createDerivationalMorpheme({
    id: "noun.deriv.lA",
    sourcePos: "Noun",
    targetPos: "Verb",
    group: "NounToVerb",
    labelKey: "actions.derivation.noun.lA",
    preview: "-lA",
    legacySuffixId: "noun.deriv.lA",
    realizationPattern: "/lA/",
  }),
  createDerivationalMorpheme({
    id: "noun.deriv.lAş",
    sourcePos: "Noun",
    targetPos: "Verb",
    group: "NounToVerb",
    labelKey: "actions.derivation.noun.lAş",
    preview: "-lAş",
    legacySuffixId: "noun.deriv.lAş",
    realizationPattern: "/lAş/",
  }),
  createDerivationalMorpheme({
    id: "noun.deriv.lAn",
    sourcePos: "Noun",
    targetPos: "Verb",
    group: "NounToVerb",
    labelKey: "actions.derivation.noun.lAn",
    preview: "-lAn",
    legacySuffixId: "noun.deriv.lAn",
    realizationPattern: "/lAn/",
  }),
  createDerivationalMorpheme({
    id: "noun.deriv.Al",
    sourcePos: "Noun",
    targetPos: "Verb",
    group: "NounToVerb",
    labelKey: "actions.derivation.noun.Al",
    preview: "-Al",
    legacySuffixId: "noun.deriv.Al",
    realizationPattern: "/Al/",
  }),
  createDerivationalMorpheme({
    id: "noun.deriv.sA",
    sourcePos: "Noun",
    targetPos: "Verb",
    group: "NounToVerb",
    labelKey: "actions.derivation.noun.sA",
    preview: "-sA",
    legacySuffixId: "noun.deriv.sA",
    realizationPattern: "/sA/",
  }),
  createDerivationalMorpheme({
    id: "verb.deriv.GI",
    sourcePos: "Verb",
    targetPos: "Noun",
    group: "VerbToNoun",
    labelKey: "actions.derivation.verb.GI",
    preview: "-GI",
    legacySuffixId: "verb.deriv.GI",
    realizationPattern: "/GI/",
    phonologyTriggers: ["consonant_assimilation"],
  }),
  createDerivationalMorpheme({
    id: "verb.deriv.ICI",
    sourcePos: "Verb",
    targetPos: "Noun",
    group: "VerbToNoun",
    labelKey: "actions.derivation.verb.ICI",
    preview: "-ICI",
    legacySuffixId: "verb.deriv.ICI",
    realizationPattern: "/ICI/",
    phonologyTriggers: ["consonant_assimilation"],
  }),
  createDerivationalMorpheme({
    id: "verb.deriv.mA",
    sourcePos: "Verb",
    targetPos: "Noun",
    group: "VerbToNoun",
    labelKey: "actions.derivation.verb.mA",
    preview: "-mA",
    legacySuffixId: "verb.deriv.mA",
    realizationPattern: "/mA/",
  }),
  createDerivationalMorpheme({
    id: "verb.deriv.Iş",
    sourcePos: "Verb",
    targetPos: "Noun",
    group: "VerbToNoun",
    labelKey: "actions.derivation.verb.Iş",
    preview: "-Iş",
    legacySuffixId: "verb.deriv.Iş",
    realizationPattern: "/Iş/",
  }),
  createDerivationalMorpheme({
    id: "verb.deriv.Ak",
    sourcePos: "Verb",
    targetPos: "Noun",
    group: "VerbToNoun",
    labelKey: "actions.derivation.verb.Ak",
    preview: "-Ak",
    legacySuffixId: "verb.deriv.Ak",
    realizationPattern: "/Ak/",
  }),
  createDerivationalMorpheme({
    id: "verb.deriv.Im",
    sourcePos: "Verb",
    targetPos: "Noun",
    group: "VerbToNoun",
    labelKey: "actions.derivation.verb.Im",
    preview: "-Im",
    legacySuffixId: "verb.deriv.Im",
    realizationPattern: "/Im/",
  }),
  createDerivationalMorpheme({
    id: "verb.voice.DIr",
    sourcePos: "Verb",
    targetPos: "Verb",
    group: "VerbToVerb",
    labelKey: "actions.derivation.voice.DIr",
    preview: "-DIr",
    legacySuffixId: "verb.voice.DIr",
    realizationPattern: "/DIr/",
    phonologyTriggers: ["consonant_assimilation"],
  }),
  createDerivationalMorpheme({
    id: "verb.voice.Il",
    sourcePos: "Verb",
    targetPos: "Verb",
    group: "VerbToVerb",
    labelKey: "actions.derivation.voice.Il",
    preview: "-Il",
    legacySuffixId: "verb.voice.Il",
    realizationPattern: "/Il/",
  }),
  createDerivationalMorpheme({
    id: "verb.voice.In",
    sourcePos: "Verb",
    targetPos: "Verb",
    group: "VerbToVerb",
    labelKey: "actions.derivation.voice.In",
    preview: "-In",
    legacySuffixId: "verb.voice.In",
    realizationPattern: "/In/",
  }),
  createDerivationalMorpheme({
    id: "verb.voice.Iş",
    sourcePos: "Verb",
    targetPos: "Verb",
    group: "VerbToVerb",
    labelKey: "actions.derivation.voice.Iş",
    preview: "-Iş",
    legacySuffixId: "verb.voice.Iş",
    realizationPattern: "/Iş/",
  }),
  createInflectionMorpheme({
    id: "noun.number.pl",
    category: "number",
    slot: "noun_number",
    pos: "Noun",
    group: "NounInflection",
    labelKey: "actions.noun.number.pl",
    preview: "-lAr",
    legacySuffixId: "noun.inflection.lAr",
    realizationPattern: "/lAr/",
    setsFeatures: { number: "pl" },
  }),
  createInflectionMorpheme({
    id: "noun.possessive.p1sg",
    category: "possessive",
    slot: "noun_possessive",
    pos: "Noun",
    group: "NounInflection",
    labelKey: "actions.noun.possessive.p1sg",
    preview: "-(I)m",
    legacySuffixId: "noun.inflection.possessive1sg",
    realizationPattern: "/Im/",
    setsFeatures: { possessive: "p1sg" },
  }),
  createInflectionMorpheme({
    id: "noun.possessive.p2sg",
    category: "possessive",
    slot: "noun_possessive",
    pos: "Noun",
    group: "NounInflection",
    labelKey: "actions.noun.possessive.p2sg",
    preview: "-(I)n",
    legacySuffixId: "noun.inflection.possessive2sg",
    realizationPattern: "/In/",
    setsFeatures: { possessive: "p2sg" },
  }),
  createInflectionMorpheme({
    id: "noun.possessive.p3sg",
    category: "possessive",
    slot: "noun_possessive",
    pos: "Noun",
    group: "NounInflection",
    labelKey: "actions.noun.possessive.p3sg",
    preview: "-(s)I",
    legacySuffixId: "noun.inflection.possessive3sg",
    realizationPattern: "/I/",
    phonologyTriggers: ["buffer_s", "consonant_mutation_trigger"],
    setsFeatures: { possessive: "p3sg" },
  }),
  createInflectionMorpheme({
    id: "noun.possessive.p1pl",
    category: "possessive",
    slot: "noun_possessive",
    pos: "Noun",
    group: "NounInflection",
    labelKey: "actions.noun.possessive.p1pl",
    preview: "-(I)mIz",
    legacySuffixId: "noun.inflection.possessive1pl",
    realizationPattern: "/ImIz/",
    setsFeatures: { possessive: "p1pl" },
  }),
  createInflectionMorpheme({
    id: "noun.possessive.p2pl",
    category: "possessive",
    slot: "noun_possessive",
    pos: "Noun",
    group: "NounInflection",
    labelKey: "actions.noun.possessive.p2pl",
    preview: "-(I)nIz",
    legacySuffixId: "noun.inflection.possessive2pl",
    realizationPattern: "/InIz/",
    setsFeatures: { possessive: "p2pl" },
  }),
  createInflectionMorpheme({
    id: "noun.possessive.p3pl",
    category: "possessive",
    slot: "noun_possessive",
    pos: "Noun",
    group: "NounInflection",
    labelKey: "actions.noun.possessive.p3pl",
    preview: "-lArI",
    legacySuffixId: "noun.inflection.possessive3pl",
    realizationPattern: "/lArI/",
    setsFeatures: { possessive: "p3pl" },
  }),
  createInflectionMorpheme({
    id: "noun.case.acc",
    category: "case",
    slot: "noun_case",
    pos: "Noun",
    group: "NounInflection",
    labelKey: "actions.noun.case.acc",
    preview: "-(y/n)I",
    legacySuffixId: "noun.inflection.accusative",
    realizationPattern: "/I/",
    phonologyTriggers: ["buffer_y", "consonant_mutation_trigger"],
    setsFeatures: { case: "acc" },
  }),
  createInflectionMorpheme({
    id: "noun.case.dat",
    category: "case",
    slot: "noun_case",
    pos: "Noun",
    group: "NounInflection",
    labelKey: "actions.noun.case.dat",
    preview: "-(y/n)A",
    legacySuffixId: "noun.inflection.dative",
    realizationPattern: "/A/",
    phonologyTriggers: ["buffer_y", "consonant_mutation_trigger"],
    setsFeatures: { case: "dat" },
  }),
  createInflectionMorpheme({
    id: "noun.case.loc",
    category: "case",
    slot: "noun_case",
    pos: "Noun",
    group: "NounInflection",
    labelKey: "actions.noun.case.loc",
    preview: "-DA",
    legacySuffixId: "noun.inflection.locative",
    realizationPattern: "/DA/",
    phonologyTriggers: ["consonant_assimilation"],
    setsFeatures: { case: "loc" },
  }),
  createInflectionMorpheme({
    id: "noun.case.abl",
    category: "case",
    slot: "noun_case",
    pos: "Noun",
    group: "NounInflection",
    labelKey: "actions.noun.case.abl",
    preview: "-DAn",
    legacySuffixId: "noun.inflection.ablative",
    realizationPattern: "/DAn/",
    phonologyTriggers: ["consonant_assimilation"],
    setsFeatures: { case: "abl" },
  }),
  createInflectionMorpheme({
    id: "noun.case.gen",
    category: "case",
    slot: "noun_case",
    pos: "Noun",
    group: "NounInflection",
    labelKey: "actions.noun.case.gen",
    preview: "-(n)In",
    legacySuffixId: "noun.inflection.genitive",
    realizationPattern: "/In/",
    phonologyTriggers: ["buffer_n", "consonant_mutation_trigger"],
    setsFeatures: { case: "gen" },
  }),
  createInflectionMorpheme({
    id: "verb.polarity.neg",
    category: "polarity",
    slot: "verb_polarity",
    pos: "Verb",
    group: "VerbInflection",
    labelKey: "actions.verb.polarity.neg",
    preview: "-mA",
    legacySuffixId: "verb.inflection.negative",
    realizationPattern: "/mA/",
    setsFeatures: { polarity: "negative" },
  }),
  createInflectionMorpheme({
    id: "verb.tam.aor",
    category: "tam",
    slot: "verb_tam",
    pos: "Verb",
    group: "VerbInflection",
    labelKey: "actions.verb.tam.aor",
    preview: "-(A/I)r",
    legacySuffixId: "verb.inflection.aor",
    realizationPattern: "/Ar/",
    setsFeatures: { tam: "aor" },
  }),
  createInflectionMorpheme({
    id: "verb.tam.prog",
    category: "tam",
    slot: "verb_tam",
    pos: "Verb",
    group: "VerbInflection",
    labelKey: "actions.verb.tam.prog",
    preview: "-Iyor",
    legacySuffixId: "verb.inflection.progressive",
    realizationPattern: "/Iyor/",
    setsFeatures: { tam: "prog" },
  }),
  createInflectionMorpheme({
    id: "verb.tam.past",
    category: "tam",
    slot: "verb_tam",
    pos: "Verb",
    group: "VerbInflection",
    labelKey: "actions.verb.tam.past",
    preview: "-DI",
    legacySuffixId: "verb.inflection.past",
    realizationPattern: "/DI/",
    phonologyTriggers: ["consonant_assimilation"],
    setsFeatures: { tam: "past" },
  }),
  createInflectionMorpheme({
    id: "verb.tam.fut",
    category: "tam",
    slot: "verb_tam",
    pos: "Verb",
    group: "VerbInflection",
    labelKey: "actions.verb.tam.future",
    preview: "-(y)AcAk",
    legacySuffixId: "verb.inflection.future",
    realizationPattern: "/AcAk/",
    phonologyTriggers: ["buffer_y"],
    setsFeatures: { tam: "fut" },
  }),
  createInflectionMorpheme({
    id: "verb.agreement.1sg",
    category: "agreement",
    slot: "verb_agreement",
    pos: "Verb",
    group: "VerbInflection",
    labelKey: "actions.verb.agreement.1sg",
    preview: "-(I)m",
    legacySuffixId: "verb.inflection.1sg",
    realizationPattern: "/Im/",
    phonologyTriggers: ["consonant_mutation_trigger"],
    setsFeatures: { agreement: "1sg" },
  }),
  createInflectionMorpheme({
    id: "verb.agreement.2sg",
    category: "agreement",
    slot: "verb_agreement",
    pos: "Verb",
    group: "VerbInflection",
    labelKey: "actions.verb.agreement.2sg",
    preview: "-sIn",
    legacySuffixId: "verb.inflection.2sg",
    realizationPattern: "/sIn/",
    setsFeatures: { agreement: "2sg" },
  }),
  createInflectionMorpheme({
    id: "verb.agreement.1pl",
    category: "agreement",
    slot: "verb_agreement",
    pos: "Verb",
    group: "VerbInflection",
    labelKey: "actions.verb.agreement.1pl",
    preview: "-(I)z/-k",
    legacySuffixId: "verb.inflection.1pl",
    realizationPattern: "/Iz/",
    phonologyTriggers: ["consonant_mutation_trigger"],
    setsFeatures: { agreement: "1pl" },
  }),
  createInflectionMorpheme({
    id: "verb.agreement.2pl",
    category: "agreement",
    slot: "verb_agreement",
    pos: "Verb",
    group: "VerbInflection",
    labelKey: "actions.verb.agreement.2pl",
    preview: "-sInIz",
    legacySuffixId: "verb.inflection.2pl",
    realizationPattern: "/sInIz/",
    setsFeatures: { agreement: "2pl" },
  }),
  createInflectionMorpheme({
    id: "verb.agreement.3pl",
    category: "agreement",
    slot: "verb_agreement",
    pos: "Verb",
    group: "VerbInflection",
    labelKey: "actions.verb.agreement.3pl",
    preview: "-lAr",
    legacySuffixId: "verb.inflection.3pl",
    realizationPattern: "/lAr/",
    setsFeatures: { agreement: "3pl" },
  }),
];
