import {
  type MorphCategory,
  type MorphemeDefinition,
  type MorphemeSlot,
  type PartOfSpeech,
  type RuleId,
} from "./types";

type MorphemeSeed = {
  id: string;
  labelKey: string;
  preview: string;
  legacySuffixId?: string;
  derivationFamily?: string;
  derivationRepeatPolicy?: MorphemeDefinition["derivationRepeatPolicy"];
  naturalnessWeight?: number;
  realizationPattern: string;
  phonologyTriggers?: RuleId[];
  requires?: MorphemeDefinition["requires"];
  blocks?: MorphemeDefinition["blocks"];
  conflictsWithMorphemeIds?: string[];
  setsFeatures?: MorphemeDefinition["setsFeatures"];
};

function createInflectionMorpheme(
  base: MorphemeSeed & {
    category: MorphemeDefinition["category"];
    slot: MorphemeSlot;
    pos: PartOfSpeech;
    sourceCategories?: MorphCategory[];
    targetCategory?: MorphCategory;
    group: string;
    hidden?: boolean;
  },
): MorphemeDefinition {
  return {
    id: base.id,
    kind: "inflectional",
    category: base.category,
    slot: base.slot,
    sourcePos: base.pos,
    targetPos: base.pos,
    sourceCategories:
      base.sourceCategories ??
      (base.pos === "Noun"
        ? ["Noun", "VerbalNoun", "Participle"]
        : ["Verb"]),
    targetCategory: base.targetCategory ?? (base.pos as MorphCategory),
    group: base.group,
    labelKey: base.labelKey,
    preview: base.preview,
    hidden: base.hidden,
    legacySuffixId: base.legacySuffixId,
    requires: base.requires,
    blocks: base.blocks,
    conflictsWithMorphemeIds: base.conflictsWithMorphemeIds,
    derivationFamily: base.derivationFamily,
    derivationRepeatPolicy: base.derivationRepeatPolicy,
    naturalnessWeight: base.naturalnessWeight,
    realizationPattern: base.realizationPattern,
    phonologyTriggers: base.phonologyTriggers ?? [],
    setsFeatures: base.setsFeatures ?? {},
  };
}

function createDerivationalMorpheme(
  base: MorphemeSeed & {
    sourcePos: PartOfSpeech;
    targetPos: PartOfSpeech;
    sourceCategories?: MorphCategory[];
    targetCategory?: MorphCategory;
    group: string;
  },
): MorphemeDefinition {
  return {
    id: base.id,
    kind: "derivational",
    category: "derivation",
    slot: "derivation",
    sourcePos: base.sourcePos,
    targetPos: base.targetPos,
    sourceCategories: base.sourceCategories ?? [base.sourcePos as MorphCategory],
    targetCategory: base.targetCategory ?? (base.targetPos as MorphCategory),
    group: base.group,
    labelKey: base.labelKey,
    preview: base.preview,
    legacySuffixId: base.legacySuffixId,
    requires: base.requires,
    blocks: base.blocks,
    conflictsWithMorphemeIds: base.conflictsWithMorphemeIds,
    derivationFamily: base.derivationFamily,
    derivationRepeatPolicy: base.derivationRepeatPolicy,
    naturalnessWeight: base.naturalnessWeight,
    realizationPattern: base.realizationPattern,
    phonologyTriggers: base.phonologyTriggers ?? [],
    setsFeatures: {},
  };
}

function createNonfiniteMorpheme(
  base: MorphemeSeed & {
    targetPos: PartOfSpeech;
    targetCategory: MorphCategory;
    group: string;
  },
): MorphemeDefinition {
  return {
    id: base.id,
    kind: "nonfinite",
    category: "nonfinite",
    slot: "verb_nonfinite",
    sourcePos: "Verb",
    targetPos: base.targetPos,
    sourceCategories: ["Verb"],
    targetCategory: base.targetCategory,
    group: base.group,
    labelKey: base.labelKey,
    preview: base.preview,
    legacySuffixId: base.legacySuffixId,
    requires: base.requires,
    blocks: base.blocks,
    conflictsWithMorphemeIds: base.conflictsWithMorphemeIds,
    derivationFamily: base.derivationFamily,
    derivationRepeatPolicy: base.derivationRepeatPolicy,
    naturalnessWeight: base.naturalnessWeight,
    realizationPattern: base.realizationPattern,
    phonologyTriggers: base.phonologyTriggers ?? [],
    setsFeatures: {},
  };
}

export const MORPHEME_CATALOG: MorphemeDefinition[] = [
  createDerivationalMorpheme({
    id: "adjective.deriv.lIk",
    sourcePos: "Noun",
    sourceCategories: ["Adjective"],
    targetPos: "Noun",
    group: "AdjectiveToNoun",
    labelKey: "actions.derivation.adjective.lIk",
    preview: "-lIk",
    derivationFamily: "nominalizer.lIk",
    derivationRepeatPolicy: "once_per_chain",
    naturalnessWeight: 88,
    realizationPattern: "/lIk/",
  }),
  createDerivationalMorpheme({
    id: "adjective.deriv.lI",
    sourcePos: "Noun",
    sourceCategories: ["Adjective"],
    targetPos: "Noun",
    group: "AdjectiveToNoun",
    labelKey: "actions.derivation.adjective.lI",
    preview: "-lI",
    derivationFamily: "qualitative.lI",
    derivationRepeatPolicy: "once_per_chain",
    naturalnessWeight: 76,
    realizationPattern: "/lI/",
  }),
  createDerivationalMorpheme({
    id: "adjective.deriv.lAş",
    sourcePos: "Noun",
    sourceCategories: ["Adjective"],
    targetPos: "Verb",
    group: "AdjectiveToVerb",
    labelKey: "actions.derivation.adjective.lAş",
    preview: "-lAş",
    derivationFamily: "inchoative.lAş",
    derivationRepeatPolicy: "once_per_chain",
    naturalnessWeight: 82,
    realizationPattern: "/lAş/",
  }),
  createDerivationalMorpheme({
    id: "adjective.deriv.lAştır",
    sourcePos: "Noun",
    sourceCategories: ["Adjective"],
    targetPos: "Verb",
    group: "AdjectiveToVerb",
    labelKey: "actions.derivation.adjective.lAştır",
    preview: "-lAştır",
    derivationFamily: "causative.lAştır",
    derivationRepeatPolicy: "once_per_chain",
    naturalnessWeight: 74,
    realizationPattern: "/lAştır/",
    phonologyTriggers: ["consonant_assimilation"],
  }),
  createDerivationalMorpheme({
    id: "adjective.deriv.CA",
    sourcePos: "Noun",
    sourceCategories: ["Adjective"],
    targetPos: "Noun",
    targetCategory: "Adverb",
    group: "AdjectiveToAdverb",
    labelKey: "actions.derivation.adjective.CA",
    preview: "-CA",
    derivationFamily: "adverbial.CA",
    derivationRepeatPolicy: "once_per_chain",
    naturalnessWeight: 84,
    realizationPattern: "/CA/",
    phonologyTriggers: ["consonant_assimilation"],
  }),
  createDerivationalMorpheme({
    id: "noun.deriv.lIk",
    sourcePos: "Noun",
    targetPos: "Noun",
    group: "NounToNoun",
    labelKey: "actions.derivation.noun.lIk",
    preview: "-lIk",
    derivationFamily: "nominalizer.lIk",
    derivationRepeatPolicy: "once_per_chain",
    naturalnessWeight: 90,
    legacySuffixId: "noun.deriv.lIk",
    realizationPattern: "/lIk/",
  }),
  createDerivationalMorpheme({
    id: "noun.deriv.lI",
    sourcePos: "Noun",
    targetPos: "Noun",
    group: "NounToNoun",
    labelKey: "actions.derivation.noun.lI",
    preview: "-lI",
    derivationFamily: "qualitative.lI",
    derivationRepeatPolicy: "once_per_chain",
    naturalnessWeight: 82,
    legacySuffixId: "noun.deriv.lI",
    realizationPattern: "/lI/",
  }),
  createDerivationalMorpheme({
    id: "noun.deriv.sIz",
    sourcePos: "Noun",
    targetPos: "Noun",
    group: "NounToNoun",
    labelKey: "actions.derivation.noun.sIz",
    preview: "-sIz",
    derivationFamily: "privative.sIz",
    derivationRepeatPolicy: "once_per_chain",
    naturalnessWeight: 80,
    legacySuffixId: "noun.deriv.sIz",
    realizationPattern: "/sIz/",
  }),
  createDerivationalMorpheme({
    id: "noun.deriv.CI",
    sourcePos: "Noun",
    targetPos: "Noun",
    group: "NounToNoun",
    labelKey: "actions.derivation.noun.CI",
    preview: "-CI",
    derivationFamily: "agentive.CI",
    derivationRepeatPolicy: "once_per_chain",
    naturalnessWeight: 78,
    legacySuffixId: "noun.deriv.CI",
    realizationPattern: "/CI/",
    phonologyTriggers: ["consonant_assimilation"],
  }),
  createDerivationalMorpheme({
    id: "noun.deriv.DAş",
    sourcePos: "Noun",
    targetPos: "Noun",
    group: "NounToNoun",
    labelKey: "actions.derivation.noun.DAş",
    preview: "-DAş",
    derivationFamily: "comitative.DAş",
    derivationRepeatPolicy: "once_per_chain",
    naturalnessWeight: 56,
    legacySuffixId: "noun.deriv.DAş",
    realizationPattern: "/DAş/",
    phonologyTriggers: ["consonant_assimilation"],
  }),
  createDerivationalMorpheme({
    id: "noun.deriv.lA",
    sourcePos: "Noun",
    targetPos: "Verb",
    group: "NounToVerb",
    labelKey: "actions.derivation.noun.lA",
    preview: "-lA",
    derivationFamily: "verbalizer.lA",
    derivationRepeatPolicy: "once_per_chain",
    naturalnessWeight: 74,
    legacySuffixId: "noun.deriv.lA",
    realizationPattern: "/lA/",
  }),
  createDerivationalMorpheme({
    id: "noun.deriv.lAş",
    sourcePos: "Noun",
    targetPos: "Verb",
    group: "NounToVerb",
    labelKey: "actions.derivation.noun.lAş",
    preview: "-lAş",
    derivationFamily: "inchoative.lAş",
    derivationRepeatPolicy: "once_per_chain",
    naturalnessWeight: 70,
    legacySuffixId: "noun.deriv.lAş",
    realizationPattern: "/lAş/",
  }),
  createDerivationalMorpheme({
    id: "noun.deriv.lAn",
    sourcePos: "Noun",
    targetPos: "Verb",
    group: "NounToVerb",
    labelKey: "actions.derivation.noun.lAn",
    preview: "-lAn",
    derivationFamily: "become.lAn",
    derivationRepeatPolicy: "once_per_chain",
    naturalnessWeight: 54,
    legacySuffixId: "noun.deriv.lAn",
    realizationPattern: "/lAn/",
  }),
  createDerivationalMorpheme({
    id: "noun.deriv.Al",
    sourcePos: "Noun",
    targetPos: "Verb",
    group: "NounToVerb",
    labelKey: "actions.derivation.noun.Al",
    preview: "-Al",
    derivationFamily: "acquire.Al",
    derivationRepeatPolicy: "once_per_chain",
    naturalnessWeight: 42,
    legacySuffixId: "noun.deriv.Al",
    realizationPattern: "/Al/",
  }),
  createDerivationalMorpheme({
    id: "noun.deriv.sA",
    sourcePos: "Noun",
    targetPos: "Verb",
    group: "NounToVerb",
    labelKey: "actions.derivation.noun.sA",
    preview: "-sA",
    derivationFamily: "desiderative.sA",
    derivationRepeatPolicy: "once_per_chain",
    naturalnessWeight: 36,
    legacySuffixId: "noun.deriv.sA",
    realizationPattern: "/sA/",
  }),
  createDerivationalMorpheme({
    id: "verb.deriv.GI",
    sourcePos: "Verb",
    targetPos: "Noun",
    group: "VerbToNoun",
    labelKey: "actions.derivation.verb.GI",
    preview: "-GI",
    derivationFamily: "nominalizer.GI",
    derivationRepeatPolicy: "once_per_chain",
    naturalnessWeight: 62,
    legacySuffixId: "verb.deriv.GI",
    realizationPattern: "/GI/",
    phonologyTriggers: ["consonant_assimilation"],
  }),
  createDerivationalMorpheme({
    id: "verb.deriv.ICI",
    sourcePos: "Verb",
    targetPos: "Noun",
    group: "VerbToNoun",
    labelKey: "actions.derivation.verb.ICI",
    preview: "-(y)ICI",
    derivationFamily: "agentive.CI",
    derivationRepeatPolicy: "once_per_chain",
    naturalnessWeight: 76,
    legacySuffixId: "verb.deriv.ICI",
    realizationPattern: "/ICI/",
    phonologyTriggers: [
      "buffer_y",
      "consonant_assimilation",
      "consonant_mutation_trigger",
    ],
  }),
  createDerivationalMorpheme({
    id: "verb.deriv.mA",
    sourcePos: "Verb",
    targetPos: "Noun",
    group: "VerbToNoun",
    labelKey: "actions.derivation.verb.mA",
    preview: "-mA",
    derivationFamily: "nominalizer.mA",
    derivationRepeatPolicy: "once_per_chain",
    naturalnessWeight: 86,
    legacySuffixId: "verb.deriv.mA",
    realizationPattern: "/mA/",
  }),
  createDerivationalMorpheme({
    id: "verb.deriv.Iş",
    sourcePos: "Verb",
    targetPos: "Noun",
    group: "VerbToNoun",
    labelKey: "actions.derivation.verb.Iş",
    preview: "-Iş",
    derivationFamily: "nominalizer.Iş",
    derivationRepeatPolicy: "once_per_chain",
    naturalnessWeight: 80,
    legacySuffixId: "verb.deriv.Iş",
    realizationPattern: "/Iş/",
    phonologyTriggers: ["consonant_mutation_trigger"],
  }),
  createDerivationalMorpheme({
    id: "verb.deriv.Ak",
    sourcePos: "Verb",
    targetPos: "Noun",
    group: "VerbToNoun",
    labelKey: "actions.derivation.verb.Ak",
    preview: "-Ak",
    derivationFamily: "nominalizer.Ak",
    derivationRepeatPolicy: "once_per_chain",
    naturalnessWeight: 58,
    legacySuffixId: "verb.deriv.Ak",
    realizationPattern: "/Ak/",
    phonologyTriggers: ["consonant_mutation_trigger"],
  }),
  createDerivationalMorpheme({
    id: "verb.deriv.Im",
    sourcePos: "Verb",
    targetPos: "Noun",
    group: "VerbToNoun",
    labelKey: "actions.derivation.verb.Im",
    preview: "-Im",
    derivationFamily: "nominalizer.Im",
    derivationRepeatPolicy: "once_per_chain",
    naturalnessWeight: 78,
    legacySuffixId: "verb.deriv.Im",
    realizationPattern: "/Im/",
    phonologyTriggers: ["consonant_mutation_trigger"],
  }),
  createDerivationalMorpheme({
    id: "verb.voice.DIr",
    sourcePos: "Verb",
    targetPos: "Verb",
    group: "VerbToVerb",
    labelKey: "actions.derivation.voice.DIr",
    preview: "-DIr",
    naturalnessWeight: 70,
    legacySuffixId: "verb.voice.DIr",
    realizationPattern: "/DIr/",
    phonologyTriggers: ["consonant_assimilation"],
  }),
  createDerivationalMorpheme({
    id: "verb.voice.Il",
    sourcePos: "Verb",
    targetPos: "Verb",
    group: "VerbToVerb",
    labelKey: "actions.derivation.voice.Il",
    preview: "-Il",
    naturalnessWeight: 66,
    legacySuffixId: "verb.voice.Il",
    conflictsWithMorphemeIds: ["verb.voice.In", "verb.voice.Iş"],
    realizationPattern: "/Il/",
    phonologyTriggers: ["consonant_mutation_trigger"],
  }),
  createDerivationalMorpheme({
    id: "verb.voice.In",
    sourcePos: "Verb",
    targetPos: "Verb",
    group: "VerbToVerb",
    labelKey: "actions.derivation.voice.In",
    preview: "-In",
    naturalnessWeight: 44,
    legacySuffixId: "verb.voice.In",
    conflictsWithMorphemeIds: ["verb.voice.Il", "verb.voice.Iş"],
    realizationPattern: "/In/",
    phonologyTriggers: ["consonant_mutation_trigger"],
  }),
  createDerivationalMorpheme({
    id: "verb.voice.Iş",
    sourcePos: "Verb",
    targetPos: "Verb",
    group: "VerbToVerb",
    labelKey: "actions.derivation.voice.Iş",
    preview: "-Iş",
    naturalnessWeight: 46,
    legacySuffixId: "verb.voice.Iş",
    conflictsWithMorphemeIds: ["verb.voice.Il", "verb.voice.In"],
    realizationPattern: "/Iş/",
    phonologyTriggers: ["consonant_mutation_trigger"],
  }),
  createNonfiniteMorpheme({
    id: "verb.nonfinite.verbalNoun.mA",
    targetPos: "Noun",
    targetCategory: "VerbalNoun",
    group: "VerbalNoun",
    labelKey: "actions.nonfinite.verbalNoun.mA",
    preview: "-mA",
    naturalnessWeight: 90,
    realizationPattern: "/mA/",
  }),
  createNonfiniteMorpheme({
    id: "verb.nonfinite.verbalNoun.mAk",
    targetPos: "Noun",
    targetCategory: "VerbalNoun",
    group: "VerbalNoun",
    labelKey: "actions.nonfinite.verbalNoun.mAk",
    preview: "-mAk",
    naturalnessWeight: 84,
    realizationPattern: "/mAk/",
  }),
  createNonfiniteMorpheme({
    id: "verb.nonfinite.verbalNoun.Iş",
    targetPos: "Noun",
    targetCategory: "VerbalNoun",
    group: "VerbalNoun",
    labelKey: "actions.nonfinite.verbalNoun.Iş",
    preview: "-Iş",
    naturalnessWeight: 72,
    realizationPattern: "/Iş/",
    phonologyTriggers: ["consonant_mutation_trigger"],
  }),
  createNonfiniteMorpheme({
    id: "verb.nonfinite.participle.An",
    targetPos: "Noun",
    targetCategory: "Participle",
    group: "Participle",
    labelKey: "actions.nonfinite.participle.An",
    preview: "-An",
    naturalnessWeight: 88,
    realizationPattern: "/An/",
    phonologyTriggers: ["consonant_mutation_trigger"],
  }),
  createNonfiniteMorpheme({
    id: "verb.nonfinite.participle.mIş",
    targetPos: "Noun",
    targetCategory: "Participle",
    group: "Participle",
    labelKey: "actions.nonfinite.participle.mIş",
    preview: "-mIş",
    naturalnessWeight: 70,
    realizationPattern: "/mIş/",
  }),
  createNonfiniteMorpheme({
    id: "verb.nonfinite.participle.DIK",
    targetPos: "Noun",
    targetCategory: "Participle",
    group: "Participle",
    labelKey: "actions.nonfinite.participle.DIK",
    preview: "-DIK",
    naturalnessWeight: 82,
    realizationPattern: "/DIK/",
    phonologyTriggers: ["consonant_assimilation"],
  }),
  createNonfiniteMorpheme({
    id: "verb.nonfinite.participle.AcAk",
    targetPos: "Noun",
    targetCategory: "Participle",
    group: "Participle",
    labelKey: "actions.nonfinite.participle.AcAk",
    preview: "-(y)AcAk",
    naturalnessWeight: 80,
    realizationPattern: "/AcAk/",
    phonologyTriggers: ["buffer_y", "consonant_mutation_trigger"],
  }),
  createNonfiniteMorpheme({
    id: "verb.nonfinite.converb.Ip",
    targetPos: "Verb",
    targetCategory: "Converb",
    group: "Converb",
    labelKey: "actions.nonfinite.converb.Ip",
    preview: "-(y)Ip",
    naturalnessWeight: 82,
    realizationPattern: "/Ip/",
    phonologyTriggers: ["buffer_y", "consonant_mutation_trigger"],
  }),
  createNonfiniteMorpheme({
    id: "verb.nonfinite.converb.IncA",
    targetPos: "Verb",
    targetCategory: "Converb",
    group: "Converb",
    labelKey: "actions.nonfinite.converb.IncA",
    preview: "-(y)IncA",
    naturalnessWeight: 78,
    realizationPattern: "/IncA/",
    phonologyTriggers: ["buffer_y", "consonant_mutation_trigger"],
  }),
  createNonfiniteMorpheme({
    id: "verb.nonfinite.converb.ArAk",
    targetPos: "Verb",
    targetCategory: "Converb",
    group: "Converb",
    labelKey: "actions.nonfinite.converb.ArAk",
    preview: "-(y)ArAk",
    naturalnessWeight: 74,
    realizationPattern: "/ArAk/",
    phonologyTriggers: ["buffer_y", "consonant_mutation_trigger"],
  }),
  createInflectionMorpheme({
    id: "noun.number.pl",
    category: "number",
    slot: "noun_number",
    pos: "Noun",
    group: "NounInflection",
    labelKey: "actions.noun.number.pl",
    preview: "-lAr",
    legacySuffixId: "noun.inflection.lAr",
    realizationPattern: "/lAr/",
    setsFeatures: { number: "pl" },
  }),
  createInflectionMorpheme({
    id: "noun.possessive.p1sg",
    category: "possessive",
    slot: "noun_possessive",
    pos: "Noun",
    group: "NounInflection",
    labelKey: "actions.noun.possessive.p1sg",
    preview: "-(I)m",
    legacySuffixId: "noun.inflection.possessive1sg",
    realizationPattern: "/Im/",
    setsFeatures: { possessive: "p1sg" },
  }),
  createInflectionMorpheme({
    id: "noun.possessive.p2sg",
    category: "possessive",
    slot: "noun_possessive",
    pos: "Noun",
    group: "NounInflection",
    labelKey: "actions.noun.possessive.p2sg",
    preview: "-(I)n",
    legacySuffixId: "noun.inflection.possessive2sg",
    realizationPattern: "/In/",
    setsFeatures: { possessive: "p2sg" },
  }),
  createInflectionMorpheme({
    id: "noun.possessive.p3sg",
    category: "possessive",
    slot: "noun_possessive",
    pos: "Noun",
    group: "NounInflection",
    labelKey: "actions.noun.possessive.p3sg",
    preview: "-(s)I",
    legacySuffixId: "noun.inflection.possessive3sg",
    realizationPattern: "/I/",
    phonologyTriggers: ["buffer_s", "consonant_mutation_trigger"],
    setsFeatures: { possessive: "p3sg" },
  }),
  createInflectionMorpheme({
    id: "noun.possessive.p1pl",
    category: "possessive",
    slot: "noun_possessive",
    pos: "Noun",
    group: "NounInflection",
    labelKey: "actions.noun.possessive.p1pl",
    preview: "-(I)mIz",
    legacySuffixId: "noun.inflection.possessive1pl",
    realizationPattern: "/ImIz/",
    setsFeatures: { possessive: "p1pl" },
  }),
  createInflectionMorpheme({
    id: "noun.possessive.p2pl",
    category: "possessive",
    slot: "noun_possessive",
    pos: "Noun",
    group: "NounInflection",
    labelKey: "actions.noun.possessive.p2pl",
    preview: "-(I)nIz",
    legacySuffixId: "noun.inflection.possessive2pl",
    realizationPattern: "/InIz/",
    setsFeatures: { possessive: "p2pl" },
  }),
  createInflectionMorpheme({
    id: "noun.possessive.p3pl",
    category: "possessive",
    slot: "noun_possessive",
    pos: "Noun",
    group: "NounInflection",
    labelKey: "actions.noun.possessive.p3pl",
    preview: "-lArI",
    legacySuffixId: "noun.inflection.possessive3pl",
    realizationPattern: "/lArI/",
    setsFeatures: { possessive: "p3pl" },
  }),
  createInflectionMorpheme({
    id: "noun.case.acc",
    category: "case",
    slot: "noun_case",
    pos: "Noun",
    group: "NounInflection",
    labelKey: "actions.noun.case.acc",
    preview: "-(y/n)I",
    legacySuffixId: "noun.inflection.accusative",
    realizationPattern: "/I/",
    phonologyTriggers: ["buffer_y", "consonant_mutation_trigger"],
    setsFeatures: { case: "acc" },
  }),
  createInflectionMorpheme({
    id: "noun.case.dat",
    category: "case",
    slot: "noun_case",
    pos: "Noun",
    group: "NounInflection",
    labelKey: "actions.noun.case.dat",
    preview: "-(y/n)A",
    legacySuffixId: "noun.inflection.dative",
    realizationPattern: "/A/",
    phonologyTriggers: ["buffer_y", "consonant_mutation_trigger"],
    setsFeatures: { case: "dat" },
  }),
  createInflectionMorpheme({
    id: "noun.case.loc",
    category: "case",
    slot: "noun_case",
    pos: "Noun",
    group: "NounInflection",
    labelKey: "actions.noun.case.loc",
    preview: "-DA",
    legacySuffixId: "noun.inflection.locative",
    realizationPattern: "/DA/",
    phonologyTriggers: ["consonant_assimilation"],
    setsFeatures: { case: "loc" },
  }),
  createInflectionMorpheme({
    id: "noun.case.abl",
    category: "case",
    slot: "noun_case",
    pos: "Noun",
    group: "NounInflection",
    labelKey: "actions.noun.case.abl",
    preview: "-DAn",
    legacySuffixId: "noun.inflection.ablative",
    realizationPattern: "/DAn/",
    phonologyTriggers: ["consonant_assimilation"],
    setsFeatures: { case: "abl" },
  }),
  createInflectionMorpheme({
    id: "noun.case.gen",
    category: "case",
    slot: "noun_case",
    pos: "Noun",
    group: "NounInflection",
    labelKey: "actions.noun.case.gen",
    preview: "-(n)In",
    legacySuffixId: "noun.inflection.genitive",
    realizationPattern: "/In/",
    phonologyTriggers: ["buffer_n", "consonant_mutation_trigger"],
    setsFeatures: { case: "gen" },
  }),
  createInflectionMorpheme({
    id: "verb.polarity.neg",
    category: "polarity",
    slot: "verb_polarity",
    pos: "Verb",
    group: "VerbInflection",
    labelKey: "actions.verb.polarity.neg",
    preview: "-mA",
    legacySuffixId: "verb.inflection.negative",
    realizationPattern: "/mA/",
    setsFeatures: { polarity: "negative" },
  }),
  createInflectionMorpheme({
    id: "verb.tam.aor",
    category: "tam",
    slot: "verb_tam",
    pos: "Verb",
    group: "VerbInflection",
    labelKey: "actions.verb.tam.aor",
    preview: "-(A/I)r",
    legacySuffixId: "verb.inflection.aor",
    realizationPattern: "/Ar/",
    setsFeatures: { tam: "aor" },
  }),
  createInflectionMorpheme({
    id: "verb.tam.prog",
    category: "tam",
    slot: "verb_tam",
    pos: "Verb",
    group: "VerbInflection",
    labelKey: "actions.verb.tam.prog",
    preview: "-Iyor",
    legacySuffixId: "verb.inflection.progressive",
    realizationPattern: "/Iyor/",
    setsFeatures: { tam: "prog" },
  }),
  createInflectionMorpheme({
    id: "verb.tam.past",
    category: "tam",
    slot: "verb_tam",
    pos: "Verb",
    group: "VerbInflection",
    labelKey: "actions.verb.tam.past",
    preview: "-DI",
    legacySuffixId: "verb.inflection.past",
    realizationPattern: "/DI/",
    phonologyTriggers: ["consonant_assimilation"],
    setsFeatures: { tam: "past" },
  }),
  createInflectionMorpheme({
    id: "verb.tam.fut",
    category: "tam",
    slot: "verb_tam",
    pos: "Verb",
    group: "VerbInflection",
    labelKey: "actions.verb.tam.future",
    preview: "-(y)AcAk",
    legacySuffixId: "verb.inflection.future",
    realizationPattern: "/AcAk/",
    phonologyTriggers: ["buffer_y"],
    setsFeatures: { tam: "fut" },
  }),
  createInflectionMorpheme({
    id: "verb.agreement.1sg",
    category: "agreement",
    slot: "verb_agreement",
    pos: "Verb",
    group: "VerbInflection",
    labelKey: "actions.verb.agreement.1sg",
    preview: "-(I)m",
    legacySuffixId: "verb.inflection.1sg",
    realizationPattern: "/Im/",
    phonologyTriggers: ["consonant_mutation_trigger"],
    setsFeatures: { agreement: "1sg" },
  }),
  createInflectionMorpheme({
    id: "verb.agreement.2sg",
    category: "agreement",
    slot: "verb_agreement",
    pos: "Verb",
    group: "VerbInflection",
    labelKey: "actions.verb.agreement.2sg",
    preview: "-sIn",
    legacySuffixId: "verb.inflection.2sg",
    realizationPattern: "/sIn/",
    setsFeatures: { agreement: "2sg" },
  }),
  createInflectionMorpheme({
    id: "verb.agreement.1pl",
    category: "agreement",
    slot: "verb_agreement",
    pos: "Verb",
    group: "VerbInflection",
    labelKey: "actions.verb.agreement.1pl",
    preview: "-(I)z/-k",
    legacySuffixId: "verb.inflection.1pl",
    realizationPattern: "/Iz/",
    phonologyTriggers: ["consonant_mutation_trigger"],
    setsFeatures: { agreement: "1pl" },
  }),
  createInflectionMorpheme({
    id: "verb.agreement.2pl",
    category: "agreement",
    slot: "verb_agreement",
    pos: "Verb",
    group: "VerbInflection",
    labelKey: "actions.verb.agreement.2pl",
    preview: "-sInIz",
    legacySuffixId: "verb.inflection.2pl",
    realizationPattern: "/sInIz/",
    setsFeatures: { agreement: "2pl" },
  }),
  createInflectionMorpheme({
    id: "verb.agreement.3pl",
    category: "agreement",
    slot: "verb_agreement",
    pos: "Verb",
    group: "VerbInflection",
    labelKey: "actions.verb.agreement.3pl",
    preview: "-lAr",
    legacySuffixId: "verb.inflection.3pl",
    realizationPattern: "/lAr/",
    setsFeatures: { agreement: "3pl" },
  }),
  createInflectionMorpheme({
    id: "predicative.zero.3sg",
    category: "predication",
    slot: "predicative_zero",
    pos: "Noun",
    sourceCategories: ["Noun", "Adjective", "VerbalNoun", "Participle"],
    targetCategory: "Predicative",
    group: "PredicativeInflection",
    labelKey: "actions.predicative.zero.3sg",
    preview: "Ø",
    hidden: true,
    realizationPattern: "",
  }),
  createInflectionMorpheme({
    id: "predicative.agreement.1sg",
    category: "agreement",
    slot: "predicative_agreement",
    pos: "Noun",
    sourceCategories: ["Noun", "Adjective", "VerbalNoun", "Participle", "Predicative"],
    targetCategory: "Predicative",
    group: "PredicativeInflection",
    labelKey: "actions.predicative.agreement.1sg",
    preview: "1. tekil yüklem",
    realizationPattern: "/Im/",
    setsFeatures: { agreement: "1sg" },
  }),
  createInflectionMorpheme({
    id: "predicative.agreement.2sg",
    category: "agreement",
    slot: "predicative_agreement",
    pos: "Noun",
    sourceCategories: ["Noun", "Adjective", "VerbalNoun", "Participle", "Predicative"],
    targetCategory: "Predicative",
    group: "PredicativeInflection",
    labelKey: "actions.predicative.agreement.2sg",
    preview: "2. tekil yüklem",
    realizationPattern: "/sIn/",
    setsFeatures: { agreement: "2sg" },
  }),
  createInflectionMorpheme({
    id: "predicative.agreement.1pl",
    category: "agreement",
    slot: "predicative_agreement",
    pos: "Noun",
    sourceCategories: ["Noun", "Adjective", "VerbalNoun", "Participle", "Predicative"],
    targetCategory: "Predicative",
    group: "PredicativeInflection",
    labelKey: "actions.predicative.agreement.1pl",
    preview: "1. çoğul yüklem",
    realizationPattern: "/Iz/",
    setsFeatures: { agreement: "1pl" },
  }),
  createInflectionMorpheme({
    id: "predicative.agreement.2pl",
    category: "agreement",
    slot: "predicative_agreement",
    pos: "Noun",
    sourceCategories: ["Noun", "Adjective", "VerbalNoun", "Participle", "Predicative"],
    targetCategory: "Predicative",
    group: "PredicativeInflection",
    labelKey: "actions.predicative.agreement.2pl",
    preview: "2. çoğul yüklem",
    realizationPattern: "/sInIz/",
    setsFeatures: { agreement: "2pl" },
  }),
  createInflectionMorpheme({
    id: "predicative.agreement.3pl",
    category: "agreement",
    slot: "predicative_agreement",
    pos: "Noun",
    sourceCategories: ["Noun", "Adjective", "VerbalNoun", "Participle", "Predicative"],
    targetCategory: "Predicative",
    group: "PredicativeInflection",
    labelKey: "actions.predicative.agreement.3pl",
    preview: "3. çoğul yüklem",
    realizationPattern: "/lAr/",
    setsFeatures: { agreement: "3pl" },
  }),
  createInflectionMorpheme({
    id: "predicative.assertive.dIr",
    category: "assertive",
    slot: "predicative_assertive",
    pos: "Noun",
    sourceCategories: ["Noun", "Adjective", "VerbalNoun", "Participle", "Predicative"],
    targetCategory: "Predicative",
    group: "PredicativeInflection",
    labelKey: "actions.predicative.assertive.dIr",
    preview: "-DIr",
    realizationPattern: "/DIr/",
    phonologyTriggers: ["consonant_assimilation"],
  }),
];
