import { type PostfiniteOverlayDefinition } from "./types";

export const POSTFINITE_OVERLAY_CATALOG: PostfiniteOverlayDefinition[] = [
  {
    id: "postfinite.question.mI",
    kind: "postfinite",
    slot: "postfinite",
    sourceCategories: ["Noun", "Verb", "Adjective", "VerbalNoun", "Participle", "Predicative"],
    group: "PostfiniteQuestion",
    overlayType: "question",
    labelKey: "actions.postfinite.question.mI",
    preview: "mI",
    naturalnessWeight: 90,
    allowAsFirst: true,
  },
  {
    id: "postfinite.copula.idi",
    kind: "postfinite",
    slot: "postfinite",
    sourceCategories: ["Noun", "Verb", "Adjective", "VerbalNoun", "Participle", "Predicative"],
    group: "PostfiniteCopula",
    overlayType: "copula_past",
    labelKey: "actions.postfinite.copula.idi",
    preview: "idi",
    naturalnessWeight: 82,
    allowAsFirst: true,
    allowAfterQuestion: true,
  },
  {
    id: "postfinite.copula.imiş",
    kind: "postfinite",
    slot: "postfinite",
    sourceCategories: ["Noun", "Verb", "Adjective", "VerbalNoun", "Participle", "Predicative"],
    group: "PostfiniteCopula",
    overlayType: "copula_evidential",
    labelKey: "actions.postfinite.copula.imiş",
    preview: "imiş",
    naturalnessWeight: 78,
    allowAsFirst: true,
    allowAfterQuestion: true,
  },
  {
    id: "postfinite.conditional.ise",
    kind: "postfinite",
    slot: "postfinite",
    sourceCategories: ["Noun", "Verb", "Adjective", "VerbalNoun", "Participle", "Predicative"],
    group: "PostfiniteConditional",
    overlayType: "conditional",
    labelKey: "actions.postfinite.conditional.ise",
    preview: "ise",
    naturalnessWeight: 74,
    allowAsFirst: true,
    allowAfterQuestion: true,
  },
  {
    id: "postfinite.while.iken",
    kind: "postfinite",
    slot: "postfinite",
    sourceCategories: ["Noun", "Verb", "Adjective", "VerbalNoun", "Participle", "Predicative"],
    group: "PostfiniteWhile",
    overlayType: "while",
    labelKey: "actions.postfinite.while.iken",
    preview: "iken",
    naturalnessWeight: 66,
    allowAsFirst: true,
  },
];
