import { type SuffixDefinition } from "./types";

export const DEFAULT_SUFFIX_CATALOG: SuffixDefinition[] = [
  {
    id: "noun.deriv.lIk",
    archiphoneme: "/lIk/",
    sourcePos: "Noun",
    targetPos: "Noun",
    harmonyType: "4-way",
    level: "A1",
    kind: "derivational",
    group: "NounToNoun",
    rules: [],
    label: "-lık",
  },
  {
    id: "noun.deriv.lI",
    archiphoneme: "/lI/",
    sourcePos: "Noun",
    targetPos: "Noun",
    harmonyType: "4-way",
    level: "A1",
    kind: "derivational",
    group: "NounToNoun",
    rules: [],
    label: "-lı",
  },
  {
    id: "noun.deriv.sIz",
    archiphoneme: "/sIz/",
    sourcePos: "Noun",
    targetPos: "Noun",
    harmonyType: "4-way",
    level: "A1",
    kind: "derivational",
    group: "NounToNoun",
    rules: [],
    label: "-sız",
  },
  {
    id: "noun.deriv.CI",
    archiphoneme: "/CI/",
    sourcePos: "Noun",
    targetPos: "Noun",
    harmonyType: "4-way",
    level: "A1",
    kind: "derivational",
    group: "NounToNoun",
    rules: ["consonant_assimilation"],
    label: "-cı",
  },
  {
    id: "noun.deriv.DAş",
    archiphoneme: "/DAş/",
    sourcePos: "Noun",
    targetPos: "Noun",
    harmonyType: "2-way",
    level: "A2",
    kind: "derivational",
    group: "NounToNoun",
    rules: ["consonant_assimilation"],
    label: "-daş",
  },
  {
    id: "noun.deriv.lA",
    archiphoneme: "/lA/",
    sourcePos: "Noun",
    targetPos: "Verb",
    harmonyType: "2-way",
    level: "A1",
    kind: "derivational",
    group: "NounToVerb",
    rules: [],
    label: "-la",
  },
  {
    id: "noun.deriv.lAş",
    archiphoneme: "/lAş/",
    sourcePos: "Noun",
    targetPos: "Verb",
    harmonyType: "2-way",
    level: "A2",
    kind: "derivational",
    group: "NounToVerb",
    rules: [],
    label: "-laş",
  },
  {
    id: "noun.deriv.lAn",
    archiphoneme: "/lAn/",
    sourcePos: "Noun",
    targetPos: "Verb",
    harmonyType: "2-way",
    level: "A2",
    kind: "derivational",
    group: "NounToVerb",
    rules: [],
    label: "-lan",
  },
  {
    id: "noun.deriv.Al",
    archiphoneme: "/Al/",
    sourcePos: "Noun",
    targetPos: "Verb",
    harmonyType: "2-way",
    level: "B1",
    kind: "derivational",
    group: "NounToVerb",
    rules: [],
    label: "-al",
  },
  {
    id: "noun.deriv.sA",
    archiphoneme: "/sA/",
    sourcePos: "Noun",
    targetPos: "Verb",
    harmonyType: "2-way",
    level: "B1",
    kind: "derivational",
    group: "NounToVerb",
    rules: [],
    label: "-sa",
  },
  {
    id: "verb.deriv.GI",
    archiphoneme: "/GI/",
    sourcePos: "Verb",
    targetPos: "Noun",
    harmonyType: "4-way",
    level: "A2",
    kind: "derivational",
    group: "VerbToNoun",
    rules: ["consonant_assimilation"],
    label: "-gi",
  },
  {
    id: "verb.deriv.ICI",
    archiphoneme: "/ICI/",
    sourcePos: "Verb",
    targetPos: "Noun",
    harmonyType: "4-way",
    level: "B1",
    kind: "derivational",
    group: "VerbToNoun",
    rules: ["consonant_assimilation"],
    label: "-ıcı",
  },
  {
    id: "verb.deriv.mA",
    archiphoneme: "/mA/",
    sourcePos: "Verb",
    targetPos: "Noun",
    harmonyType: "2-way",
    level: "A1",
    kind: "derivational",
    group: "VerbToNoun",
    rules: [],
    label: "-ma",
  },
  {
    id: "verb.deriv.Iş",
    archiphoneme: "/Iş/",
    sourcePos: "Verb",
    targetPos: "Noun",
    harmonyType: "4-way",
    level: "A2",
    kind: "derivational",
    group: "VerbToNoun",
    rules: [],
    label: "-ış",
  },
  {
    id: "verb.deriv.Ak",
    archiphoneme: "/Ak/",
    sourcePos: "Verb",
    targetPos: "Noun",
    harmonyType: "2-way",
    level: "B1",
    kind: "derivational",
    group: "VerbToNoun",
    rules: [],
    label: "-ak",
  },
  {
    id: "verb.deriv.Im",
    archiphoneme: "/Im/",
    sourcePos: "Verb",
    targetPos: "Noun",
    harmonyType: "4-way",
    level: "B1",
    kind: "derivational",
    group: "VerbToNoun",
    rules: [],
    label: "-ım",
  },
  {
    id: "verb.voice.DIr",
    archiphoneme: "/DIr/",
    sourcePos: "Verb",
    targetPos: "Verb",
    harmonyType: "4-way",
    level: "B1",
    kind: "derivational",
    group: "VerbToVerb",
    rules: ["consonant_assimilation"],
    label: "-dır",
  },
  {
    id: "verb.voice.Il",
    archiphoneme: "/Il/",
    sourcePos: "Verb",
    targetPos: "Verb",
    harmonyType: "4-way",
    level: "B1",
    kind: "derivational",
    group: "VerbToVerb",
    rules: [],
    label: "-ıl",
  },
  {
    id: "verb.voice.In",
    archiphoneme: "/In/",
    sourcePos: "Verb",
    targetPos: "Verb",
    harmonyType: "4-way",
    level: "B1",
    kind: "derivational",
    group: "VerbToVerb",
    rules: [],
    label: "-ın",
  },
  {
    id: "verb.voice.Iş",
    archiphoneme: "/Iş/",
    sourcePos: "Verb",
    targetPos: "Verb",
    harmonyType: "4-way",
    level: "B1",
    kind: "derivational",
    group: "VerbToVerb",
    rules: [],
    label: "-ış",
  },
  {
    id: "noun.inflection.lAr",
    archiphoneme: "/lAr/",
    sourcePos: "Noun",
    targetPos: "Noun",
    harmonyType: "2-way",
    level: "A1",
    kind: "inflectional",
    group: "NounInflection",
    rules: [],
    label: "-lar",
  },
  {
    id: "noun.inflection.accusative",
    archiphoneme: "/I/",
    sourcePos: "Noun",
    targetPos: "Noun",
    harmonyType: "4-way",
    level: "A1",
    kind: "inflectional",
    group: "NounInflection",
    rules: ["buffer_y", "consonant_mutation_trigger"],
    label: "-(y)ı",
  },
  {
    id: "noun.inflection.dative",
    archiphoneme: "/A/",
    sourcePos: "Noun",
    targetPos: "Noun",
    harmonyType: "2-way",
    level: "A1",
    kind: "inflectional",
    group: "NounInflection",
    rules: ["buffer_y", "consonant_mutation_trigger"],
    label: "-(y)a",
  },
  {
    id: "noun.inflection.locative",
    archiphoneme: "/DA/",
    sourcePos: "Noun",
    targetPos: "Noun",
    harmonyType: "2-way",
    level: "A1",
    kind: "inflectional",
    group: "NounInflection",
    rules: ["consonant_assimilation"],
    label: "-da",
  },
  {
    id: "noun.inflection.ablative",
    archiphoneme: "/DAn/",
    sourcePos: "Noun",
    targetPos: "Noun",
    harmonyType: "2-way",
    level: "A2",
    kind: "inflectional",
    group: "NounInflection",
    rules: ["consonant_assimilation"],
    label: "-dan",
  },
  {
    id: "noun.inflection.genitive",
    archiphoneme: "/In/",
    sourcePos: "Noun",
    targetPos: "Noun",
    harmonyType: "4-way",
    level: "A2",
    kind: "inflectional",
    group: "NounInflection",
    rules: ["buffer_n", "consonant_mutation_trigger"],
    label: "-(n)ın",
  },
  {
    id: "noun.inflection.possessive3sg",
    archiphoneme: "/I/",
    sourcePos: "Noun",
    targetPos: "Noun",
    harmonyType: "4-way",
    level: "A2",
    kind: "inflectional",
    group: "NounInflection",
    rules: ["buffer_s", "consonant_mutation_trigger"],
    label: "-(s)ı",
  },
  {
    id: "noun.inflection.possessive1sg",
    archiphoneme: "/Im/",
    sourcePos: "Noun",
    targetPos: "Noun",
    harmonyType: "4-way",
    level: "A2",
    kind: "inflectional",
    group: "NounInflection",
    rules: ["consonant_mutation_trigger"],
    label: "-(ı)m",
  },
  {
    id: "noun.inflection.possessive2sg",
    archiphoneme: "/In/",
    sourcePos: "Noun",
    targetPos: "Noun",
    harmonyType: "4-way",
    level: "A2",
    kind: "inflectional",
    group: "NounInflection",
    rules: ["consonant_mutation_trigger"],
    label: "-(ı)n",
  },
  {
    id: "noun.inflection.possessive1pl",
    archiphoneme: "/ImIz/",
    sourcePos: "Noun",
    targetPos: "Noun",
    harmonyType: "4-way",
    level: "B1",
    kind: "inflectional",
    group: "NounInflection",
    rules: ["consonant_mutation_trigger"],
    label: "-(ı)mız",
  },
  {
    id: "noun.inflection.possessive2pl",
    archiphoneme: "/InIz/",
    sourcePos: "Noun",
    targetPos: "Noun",
    harmonyType: "4-way",
    level: "B1",
    kind: "inflectional",
    group: "NounInflection",
    rules: ["consonant_mutation_trigger"],
    label: "-(ı)nız",
  },
  {
    id: "noun.inflection.possessive3pl",
    archiphoneme: "/lArI/",
    sourcePos: "Noun",
    targetPos: "Noun",
    harmonyType: "4-way",
    level: "B1",
    kind: "inflectional",
    group: "NounInflection",
    rules: [],
    label: "-ları",
  },
  {
    id: "verb.inflection.negative",
    archiphoneme: "/mA/",
    sourcePos: "Verb",
    targetPos: "Verb",
    harmonyType: "2-way",
    level: "A1",
    kind: "inflectional",
    group: "VerbInflection",
    rules: [],
    label: "-ma",
  },
  {
    id: "verb.inflection.aor",
    archiphoneme: "/Ar/",
    sourcePos: "Verb",
    targetPos: "Verb",
    harmonyType: "2-way",
    level: "A2",
    kind: "inflectional",
    group: "VerbInflection",
    rules: [],
    label: "-(A/I)r",
  },
  {
    id: "verb.inflection.progressive",
    archiphoneme: "/Iyor/",
    sourcePos: "Verb",
    targetPos: "Verb",
    harmonyType: "4-way",
    level: "A1",
    kind: "inflectional",
    group: "VerbInflection",
    rules: [],
    label: "-iyor",
  },
  {
    id: "verb.inflection.past",
    archiphoneme: "/DI/",
    sourcePos: "Verb",
    targetPos: "Verb",
    harmonyType: "4-way",
    level: "A1",
    kind: "inflectional",
    group: "VerbInflection",
    rules: ["consonant_assimilation"],
    label: "-dı",
  },
  {
    id: "verb.inflection.future",
    archiphoneme: "/AcAk/",
    sourcePos: "Verb",
    targetPos: "Verb",
    harmonyType: "2-way",
    level: "A2",
    kind: "inflectional",
    group: "VerbInflection",
    rules: ["buffer_y"],
    label: "-(y)acak",
  },
  {
    id: "verb.inflection.1sg",
    archiphoneme: "/Im/",
    sourcePos: "Verb",
    targetPos: "Verb",
    harmonyType: "4-way",
    level: "A1",
    kind: "inflectional",
    group: "VerbInflection",
    rules: ["consonant_mutation_trigger"],
    label: "-(ı)m",
  },
  {
    id: "verb.inflection.2sg",
    archiphoneme: "/sIn/",
    sourcePos: "Verb",
    targetPos: "Verb",
    harmonyType: "4-way",
    level: "A1",
    kind: "inflectional",
    group: "VerbInflection",
    rules: [],
    label: "-sın",
  },
  {
    id: "verb.inflection.1pl",
    archiphoneme: "/Iz/",
    sourcePos: "Verb",
    targetPos: "Verb",
    harmonyType: "4-way",
    level: "A1",
    kind: "inflectional",
    group: "VerbInflection",
    rules: ["consonant_mutation_trigger"],
    label: "-(ı)z",
  },
  {
    id: "verb.inflection.2pl",
    archiphoneme: "/sInIz/",
    sourcePos: "Verb",
    targetPos: "Verb",
    harmonyType: "4-way",
    level: "A1",
    kind: "inflectional",
    group: "VerbInflection",
    rules: [],
    label: "-sınız",
  },
  {
    id: "verb.inflection.3pl",
    archiphoneme: "/lAr/",
    sourcePos: "Verb",
    targetPos: "Verb",
    harmonyType: "2-way",
    level: "A1",
    kind: "inflectional",
    group: "VerbInflection",
    rules: [],
    label: "-lar",
  },
];
